/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ChirpComingSoonRouteImport } from './routes/chirp/coming-soon';
import { Route as ChirpGalleryRouteImport } from './routes/chirp/gallery';
import { Route as ChirpGalleryImageIdRouteImport } from './routes/chirp/gallery.$imageId';
import { Route as ChirpIndexRouteImport } from './routes/chirp/index';
import { Route as ChirpLoginRouteImport } from './routes/chirp/login';
import { Route as ChirpUploadRouteImport } from './routes/chirp/upload';
import { Route as TransformerRouteImport } from './routes/transformer';

const TransformerRoute = TransformerRouteImport.update({
  id: '/transformer',
  path: '/transformer',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpIndexRoute = ChirpIndexRouteImport.update({
  id: '/chirp/',
  path: '/chirp/',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpUploadRoute = ChirpUploadRouteImport.update({
  id: '/chirp/upload',
  path: '/chirp/upload',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpLoginRoute = ChirpLoginRouteImport.update({
  id: '/chirp/login',
  path: '/chirp/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpGalleryRoute = ChirpGalleryRouteImport.update({
  id: '/chirp/gallery',
  path: '/chirp/gallery',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpComingSoonRoute = ChirpComingSoonRouteImport.update({
  id: '/chirp/coming-soon',
  path: '/chirp/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any);
const ChirpGalleryImageIdRoute = ChirpGalleryImageIdRouteImport.update({
  id: '/$imageId',
  path: '/$imageId',
  getParentRoute: () => ChirpGalleryRoute,
} as any);

export interface FileRoutesByFullPath {
  '/transformer': typeof TransformerRoute;
  '/chirp/coming-soon': typeof ChirpComingSoonRoute;
  '/chirp/gallery': typeof ChirpGalleryRouteWithChildren;
  '/chirp/login': typeof ChirpLoginRoute;
  '/chirp/upload': typeof ChirpUploadRoute;
  '/chirp': typeof ChirpIndexRoute;
  '/chirp/gallery/$imageId': typeof ChirpGalleryImageIdRoute;
}
export interface FileRoutesByTo {
  '/transformer': typeof TransformerRoute;
  '/chirp/coming-soon': typeof ChirpComingSoonRoute;
  '/chirp/gallery': typeof ChirpGalleryRouteWithChildren;
  '/chirp/login': typeof ChirpLoginRoute;
  '/chirp/upload': typeof ChirpUploadRoute;
  '/chirp': typeof ChirpIndexRoute;
  '/chirp/gallery/$imageId': typeof ChirpGalleryImageIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/transformer': typeof TransformerRoute;
  '/chirp/coming-soon': typeof ChirpComingSoonRoute;
  '/chirp/gallery': typeof ChirpGalleryRouteWithChildren;
  '/chirp/login': typeof ChirpLoginRoute;
  '/chirp/upload': typeof ChirpUploadRoute;
  '/chirp/': typeof ChirpIndexRoute;
  '/chirp/gallery/$imageId': typeof ChirpGalleryImageIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/transformer'
    | '/chirp/coming-soon'
    | '/chirp/gallery'
    | '/chirp/login'
    | '/chirp/upload'
    | '/chirp'
    | '/chirp/gallery/$imageId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/transformer'
    | '/chirp/coming-soon'
    | '/chirp/gallery'
    | '/chirp/login'
    | '/chirp/upload'
    | '/chirp'
    | '/chirp/gallery/$imageId';
  id:
    | '__root__'
    | '/transformer'
    | '/chirp/coming-soon'
    | '/chirp/gallery'
    | '/chirp/login'
    | '/chirp/upload'
    | '/chirp/'
    | '/chirp/gallery/$imageId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  TransformerRoute: typeof TransformerRoute;
  ChirpComingSoonRoute: typeof ChirpComingSoonRoute;
  ChirpGalleryRoute: typeof ChirpGalleryRouteWithChildren;
  ChirpLoginRoute: typeof ChirpLoginRoute;
  ChirpUploadRoute: typeof ChirpUploadRoute;
  ChirpIndexRoute: typeof ChirpIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transformer': {
      id: '/transformer';
      path: '/transformer';
      fullPath: '/transformer';
      preLoaderRoute: typeof TransformerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/': {
      id: '/chirp/';
      path: '/chirp';
      fullPath: '/chirp';
      preLoaderRoute: typeof ChirpIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/upload': {
      id: '/chirp/upload';
      path: '/chirp/upload';
      fullPath: '/chirp/upload';
      preLoaderRoute: typeof ChirpUploadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/login': {
      id: '/chirp/login';
      path: '/chirp/login';
      fullPath: '/chirp/login';
      preLoaderRoute: typeof ChirpLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/gallery': {
      id: '/chirp/gallery';
      path: '/chirp/gallery';
      fullPath: '/chirp/gallery';
      preLoaderRoute: typeof ChirpGalleryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/coming-soon': {
      id: '/chirp/coming-soon';
      path: '/chirp/coming-soon';
      fullPath: '/chirp/coming-soon';
      preLoaderRoute: typeof ChirpComingSoonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chirp/gallery/$imageId': {
      id: '/chirp/gallery/$imageId';
      path: '/$imageId';
      fullPath: '/chirp/gallery/$imageId';
      preLoaderRoute: typeof ChirpGalleryImageIdRouteImport;
      parentRoute: typeof ChirpGalleryRoute;
    };
  }
}

interface ChirpGalleryRouteChildren {
  ChirpGalleryImageIdRoute: typeof ChirpGalleryImageIdRoute;
}

const ChirpGalleryRouteChildren: ChirpGalleryRouteChildren = {
  ChirpGalleryImageIdRoute: ChirpGalleryImageIdRoute,
};

const ChirpGalleryRouteWithChildren = ChirpGalleryRoute._addFileChildren(
  ChirpGalleryRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  TransformerRoute: TransformerRoute,
  ChirpComingSoonRoute: ChirpComingSoonRoute,
  ChirpGalleryRoute: ChirpGalleryRouteWithChildren,
  ChirpLoginRoute: ChirpLoginRoute,
  ChirpUploadRoute: ChirpUploadRoute,
  ChirpIndexRoute: ChirpIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
